python cgem.extract_time_series.py _1.nc 0 0 1
python cgem.extract_time_series.py _1.nc 0 2 0
python cgem.extract_time_series.py _1.nc 0 4 0
python cgem.extract_time_series.py _1.nc 0 6 0
python cgem.extract_time_series.py _1.nc 0 8 0
python cgem.extract_time_series.py _1.nc 0 10 0
python cgem.extract_time_series.py _1.nc 7 0 0
python cgem.extract_time_series.py _1.nc 7 2 0
python cgem.extract_time_series.py _1.nc 7 4 0
python cgem.extract_time_series.py _1.nc 7 6 0
python cgem.extract_time_series.py _1.nc 7 8 0
python cgem.extract_time_series.py _1.nc 7 10 0
python cgem.extract_time_series.py _1.nc 28 0 0
python cgem.extract_time_series.py _1.nc 28 2 0
python cgem.extract_time_series.py _1.nc 28 4 0
python cgem.extract_time_series.py _1.nc 28 6 0
python cgem.extract_time_series.py _1.nc 28 8 0
python cgem.extract_time_series.py _1.nc 28 10 0
python cgem.extract_time_series.py _1.nc 43 0 0
python cgem.extract_time_series.py _1.nc 43 2 0
python cgem.extract_time_series.py _1.nc 43 4 0
python cgem.extract_time_series.py _1.nc 43 6 0
python cgem.extract_time_series.py _1.nc 43 8 0
python cgem.extract_time_series.py _1.nc 43 10 0
