python cgem.extract_time_series.py _1.nc 1 1 1
python cgem.extract_time_series.py _1.nc 1 4 0
python cgem.extract_time_series.py _1.nc 1 7 0
python cgem.extract_time_series.py _1.nc 4 1 0
python cgem.extract_time_series.py _1.nc 4 4 0
python cgem.extract_time_series.py _1.nc 4 7 0
python cgem.extract_time_series.py _1.nc 7 1 0
python cgem.extract_time_series.py _1.nc 7 4 0
python cgem.extract_time_series.py _1.nc 7 7 0
python cgem.extract_time_series.py _2.nc 1 1 0
python cgem.extract_time_series.py _2.nc 1 4 0
python cgem.extract_time_series.py _2.nc 1 7 0
python cgem.extract_time_series.py _2.nc 4 1 0
python cgem.extract_time_series.py _2.nc 4 4 0
python cgem.extract_time_series.py _2.nc 4 7 0
python cgem.extract_time_series.py _2.nc 7 1 0
python cgem.extract_time_series.py _2.nc 7 4 0
python cgem.extract_time_series.py _2.nc 7 7 0
python cgem.extract_time_series.py _3.nc 1 1 0
python cgem.extract_time_series.py _3.nc 1 4 0
python cgem.extract_time_series.py _3.nc 1 7 0
python cgem.extract_time_series.py _3.nc 4 1 0
python cgem.extract_time_series.py _3.nc 4 4 0
python cgem.extract_time_series.py _3.nc 4 7 0
python cgem.extract_time_series.py _3.nc 7 1 0
python cgem.extract_time_series.py _3.nc 7 4 0
python cgem.extract_time_series.py _3.nc 7 7 0
python cgem.extract_time_series.py _4.nc 1 1 0
python cgem.extract_time_series.py _4.nc 1 4 0
python cgem.extract_time_series.py _4.nc 1 7 0
python cgem.extract_time_series.py _4.nc 4 1 0
python cgem.extract_time_series.py _4.nc 4 4 0
python cgem.extract_time_series.py _4.nc 4 7 0
python cgem.extract_time_series.py _4.nc 7 1 0
python cgem.extract_time_series.py _4.nc 7 4 0
python cgem.extract_time_series.py _4.nc 7 7 0
python cgem.extract_time_series.py _5.nc 1 1 0
python cgem.extract_time_series.py _5.nc 1 4 0
python cgem.extract_time_series.py _5.nc 1 7 0
python cgem.extract_time_series.py _5.nc 4 1 0
python cgem.extract_time_series.py _5.nc 4 4 0
python cgem.extract_time_series.py _5.nc 4 7 0
python cgem.extract_time_series.py _5.nc 7 1 0
python cgem.extract_time_series.py _5.nc 7 4 0
python cgem.extract_time_series.py _5.nc 7 7 0
python cgem.extract_time_series.py _6.nc 1 1 0
python cgem.extract_time_series.py _6.nc 1 4 0
python cgem.extract_time_series.py _6.nc 1 7 0
python cgem.extract_time_series.py _6.nc 4 1 0
python cgem.extract_time_series.py _6.nc 4 4 0
python cgem.extract_time_series.py _6.nc 4 7 0
python cgem.extract_time_series.py _6.nc 7 1 0
python cgem.extract_time_series.py _6.nc 7 4 0
python cgem.extract_time_series.py _6.nc 7 7 0
python cgem.extract_time_series.py _7.nc 1 1 0
python cgem.extract_time_series.py _7.nc 1 4 0
python cgem.extract_time_series.py _7.nc 1 7 0
python cgem.extract_time_series.py _7.nc 4 1 0
python cgem.extract_time_series.py _7.nc 4 4 0
python cgem.extract_time_series.py _7.nc 4 7 0
python cgem.extract_time_series.py _7.nc 7 1 0
python cgem.extract_time_series.py _7.nc 7 4 0
python cgem.extract_time_series.py _7.nc 7 7 0
python cgem.extract_time_series.py _8.nc 1 1 0
python cgem.extract_time_series.py _8.nc 1 4 0
python cgem.extract_time_series.py _8.nc 1 7 0
python cgem.extract_time_series.py _8.nc 4 1 0
python cgem.extract_time_series.py _8.nc 4 4 0
python cgem.extract_time_series.py _8.nc 4 7 0
python cgem.extract_time_series.py _8.nc 7 1 0
python cgem.extract_time_series.py _8.nc 7 4 0
python cgem.extract_time_series.py _8.nc 7 7 0
python cgem.extract_time_series.py _9.nc 1 1 0
python cgem.extract_time_series.py _9.nc 1 4 0
python cgem.extract_time_series.py _9.nc 1 7 0
python cgem.extract_time_series.py _9.nc 4 1 0
python cgem.extract_time_series.py _9.nc 4 4 0
python cgem.extract_time_series.py _9.nc 4 7 0
python cgem.extract_time_series.py _9.nc 7 1 0
python cgem.extract_time_series.py _9.nc 7 4 0
python cgem.extract_time_series.py _9.nc 7 7 0
python cgem.extract_time_series.py _10.nc 1 1 0
python cgem.extract_time_series.py _10.nc 1 4 0
python cgem.extract_time_series.py _10.nc 1 7 0
python cgem.extract_time_series.py _10.nc 4 1 0
python cgem.extract_time_series.py _10.nc 4 4 0
python cgem.extract_time_series.py _10.nc 4 7 0
python cgem.extract_time_series.py _10.nc 7 1 0
python cgem.extract_time_series.py _10.nc 7 4 0
python cgem.extract_time_series.py _10.nc 7 7 0
python cgem.extract_time_series.py _11.nc 1 1 0
python cgem.extract_time_series.py _11.nc 1 4 0
python cgem.extract_time_series.py _11.nc 1 7 0
python cgem.extract_time_series.py _11.nc 4 1 0
python cgem.extract_time_series.py _11.nc 4 4 0
python cgem.extract_time_series.py _11.nc 4 7 0
python cgem.extract_time_series.py _11.nc 7 1 0
python cgem.extract_time_series.py _11.nc 7 4 0
python cgem.extract_time_series.py _11.nc 7 7 0
python cgem.extract_time_series.py _12.nc 1 1 0
python cgem.extract_time_series.py _12.nc 1 4 0
python cgem.extract_time_series.py _12.nc 1 7 0
python cgem.extract_time_series.py _12.nc 4 1 0
python cgem.extract_time_series.py _12.nc 4 4 0
python cgem.extract_time_series.py _12.nc 4 7 0
python cgem.extract_time_series.py _12.nc 7 1 0
python cgem.extract_time_series.py _12.nc 7 4 0
python cgem.extract_time_series.py _12.nc 7 7 0
python cgem.extract_time_series.py _13.nc 1 1 0
python cgem.extract_time_series.py _13.nc 1 4 0
python cgem.extract_time_series.py _13.nc 1 7 0
python cgem.extract_time_series.py _13.nc 4 1 0
python cgem.extract_time_series.py _13.nc 4 4 0
python cgem.extract_time_series.py _13.nc 4 7 0
python cgem.extract_time_series.py _13.nc 7 1 0
python cgem.extract_time_series.py _13.nc 7 4 0
python cgem.extract_time_series.py _13.nc 7 7 0
