python extract_time_series.py _1.nc
python extract_time_series.py _2.nc
python extract_time_series.py _3.nc
python extract_time_series.py _4.nc
python extract_time_series.py _5.nc
python extract_time_series.py _6.nc
python extract_time_series.py _7.nc
python extract_time_series.py _8.nc
python extract_time_series.py _9.nc
python extract_time_series.py _10.nc
python extract_time_series.py _11.nc
python extract_time_series.py _12.nc
python extract_time_series.py _13.nc
